# Generated by Django 2.1 on 2018-08-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_yesno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesno',
            name='first_name',
        ),
    ]
