# Generated by Django 2.1 on 2018-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_yesno_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='no',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='yes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
            ],
        ),
    ]
