# Generated by Django 2.1 on 2018-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_no_yes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yesno',
        ),
        migrations.AlterField(
            model_name='no',
            name='n',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='yes',
            name='n',
            field=models.CharField(max_length=30),
        ),
    ]
